steps:
  - name: update metadata from Github API
    module: processors/github_metadata
    module_options:
      source_directory: ./
      gh_metadata_only_missing: True

  - name: check data against awesome-selfhosted guidelines
    module: processors/awesome_lint
    module_options:
      source_directory: ./
      items_in_delegate_to_fatal: False
      licenses_files:
        - licenses.yml
        - licenses-nonfree.yml
