name: Automation
description: '[Automation](https://en.wikipedia.org/wiki/Automation) software designed
  to reduce human intervention in processes.'
related_tags:
  - Internet of Things (IoT)
delegate_to: []
external_links: []
