name: dead links/unmaintained projects checks

on:
  schedule:
    - cron: '22 22 * * *'
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  unmaintained-projects-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make awesome_lint

  link-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make url_check
